sudo: required
dist: trusty
language: node_js
node_js:
  - '7'


addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox

before_script:
  - npm install -g @angular/cli
  - npm install
  - ng build
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

script: ng test --single-run
